const CHAVE_PIX="38258022806";const FRETE=8;const ZAP="5514999999999";
const produtos=[
{id:1,cat:'smash',nome:'Smash Burguês',desc:'Pão, maionese, hambúrguer e queijo.',preco:21,foto:''},
{id:2,cat:'smash',nome:'Smash Salada',desc:'Pão, maionese, hambúrguer, queijo, alface e tomate.',preco:24,foto:''},
{id:3,cat:'smash',nome:'Smash Bacon',desc:'Pão, maionese, 2 hambúrgueres, queijo, bacon, alface e tomate.',preco:30,foto:''},
{id:4,cat:'smash',nome:'Smash Egg',desc:'Pão, maionese, ovo, hambúrguer, queijo, alface e tomate.',preco:26,foto:''},
{id:5,cat:'smash',nome:'Smash Triplo',desc:'Pão, maionese, 3 hambúrgueres, queijo, bacon, alface e tomate.',preco:35,foto:''},
{id:6,cat:'smash',nome:'Tropical',desc:'Pão, maionese, 120g hambúrguer, queijo, bacon, abacaxi caramelizado, cebola roxa e rúcula.',preco:33,foto:''},
{id:7,cat:'smash',nome:'Chicken Bacon',desc:'Pão, maionese, frango KFC, queijo, bacon, alface e tomate.',preco:30,foto:''},
{id:8,cat:'smash',nome:'Smash Tudo (Pão Francês)',desc:'Pão francês, maionese, 4 hambúrgueres, queijo prato, bacon, 3 ovos, calabresa, alface e tomate.',preco:55,foto:''},
{id:9,cat:'porcoes',nome:'Frango KFC P (350g)',desc:'Filé de frango crocante e molho especial.',preco:30,foto:''},
{id:10,cat:'porcoes',nome:'Frango KFC M (500g)',desc:'Filé de frango crocante e molho especial.',preco:50,foto:''},
{id:11,cat:'porcoes',nome:'Frango KFC G (1kg)',desc:'Filé de frango crocante e molho especial.',preco:80,foto:''},
{id:12,cat:'porcoes',nome:'Tilápia',desc:'Filé de tilápia, pão na chapa, batata frita e molho tártaro.',preco:70,foto:''},
{id:13,cat:'porcoes',nome:'Anéis de Cebola 300g',desc:'Anéis de cebola fritos crocantes.',preco:25,foto:''},
{id:14,cat:'porcoes',nome:'Filé de Frango à Parmegiana',desc:'1kg de filé de frango, 300g de batata frita, molho e queijo.',preco:80,foto:''},
{id:15,cat:'porcoes',nome:'Batata Frita 600g',desc:'Batata frita crocante.',preco:40,foto:''},
{id:16,cat:'porcoes',nome:'Batata Cheddar e Bacon',desc:'Batata frita com cheddar e bacon.',preco:55,foto:''},
{id:17,cat:'porcoes',nome:'Batata 4 Queijos',desc:'Batata frita, 4 queijos e bacon.',preco:56,foto:''},
{id:18,cat:'porcoes',nome:'Tacos Mexicanos',desc:'Tacos de carne, frango, presunto e queijo.',preco:20,foto:''},
{id:19,cat:'porcoes',nome:'Contra Filé',desc:'500g de contra filé, batata frita e torrada.',preco:110,foto:''},
{id:20,cat:'porcoes',nome:'Parmegiana de Carne',desc:'Parmegiana de carne acompanha batata frita.',preco:110,foto:''},
{id:21,cat:'porcoes',nome:'Nachos',desc:'Doritos, carne moída ou frango desfiado.',preco:55,foto:''},
{id:22,cat:'dogs',nome:'Dog Tradicional',desc:'Pão, maionese, ketchup, mostarda, 2 salsichas, purê, vinagrete e batata.',preco:17,foto:''},
{id:23,cat:'dogs',nome:'Dog Bacon',desc:'Pão, maionese, ketchup, mostarda, 2 salsichas, bacon, alface e batata palha.',preco:19,foto:''},
{id:24,cat:'dogs',nome:'Dog Vaca Louca',desc:'Pão, maionese, ketchup, mostarda, 2 salsichas, carne desfiada, queijo, catupiry, alface e batata palha.',preco:25,foto:''},
{id:25,cat:'coxinha',nome:'Coxinha Carne c/ Ovo',desc:'Coxinha de carne com ovo.',preco:10,foto:''},
{id:26,cat:'coxinha',nome:'Coxinha Presunto e Queijo',desc:'Coxinha de presunto e queijo.',preco:12,foto:''},
{id:27,cat:'coxinha',nome:'Coxinha Frango c/ Catupiry',desc:'Coxinha de frango com catupiry.',preco:10,foto:''},
{id:28,cat:'coxinha',nome:'Coxinha Carne c/ Cream Cheese',desc:'Coxinha de carne com cream cheese.',preco:12,foto:''},
{id:29,cat:'rap10',nome:'Rap 10',desc:'Massa Rap10, hambúrguer artesanal, queijo prato, molho rosé apimentado, cebola roxa, tomate, alface e rúcula.',preco:20,foto:''},
{id:30,cat:'cafe',nome:'Pão na Chapa',desc:'Pão na chapa com manteiga.',preco:6,foto:''},
{id:31,cat:'cafe',nome:'Misto Quente',desc:'Presunto e queijo.',preco:10,foto:''},
{id:32,cat:'cafe',nome:'Omelete',desc:'Omelete.',preco:10,foto:''},
{id:33,cat:'cafe',nome:'Bauru',desc:'Presunto, queijo, tomate e orégano.',preco:12,foto:''},
{id:34,cat:'cafe',nome:'Americano',desc:'Presunto, queijo e ovo.',preco:15,foto:''},
{id:35,cat:'cafe',nome:'Pão c/ Hambúrguer',desc:'Hambúrguer artesanal, queijo, alface e tomate.',preco:15,foto:''},
{id:36,cat:'cafe',nome:'Requeijão Tost',desc:'Pão, requeijão e queijo tostado.',preco:15,foto:''},
{id:37,cat:'cafe',nome:'Tapioca Frango',desc:'Frango desfiado, catupiry e milho.',preco:16,foto:''},
{id:38,cat:'cafe',nome:'Tapioca Presunto e Queijo',desc:'Presunto, queijo, tomate e requeijão.',preco:18,foto:''},
{id:39,cat:'cafe',nome:'Café Preto',desc:'Café preto.',preco:2,foto:''},
{id:40,cat:'cafe',nome:'Café c/ Leite',desc:'Café com leite.',preco:5,foto:''},
{id:41,cat:'cafe',nome:'Capuccino',desc:'Capuccino cremoso.',preco:12,foto:''},
{id:42,cat:'cafe',nome:'Vitamina',desc:'Banana, mamão, morango e maçã.',preco:13,foto:''},
{id:43,cat:'bebidas',nome:'Coca-Cola 600ml',desc:'Refrigerante Coca-Cola 600ml gelada.',preco:10,foto:''},
{id:44,cat:'bebidas',nome:'Coca-Cola 1 Litro',desc:'Refrigerante Coca-Cola 1 litro.',preco:12,foto:''},
{id:45,cat:'bebidas',nome:'Coca-Cola 2 Litros',desc:'Refrigerante Coca-Cola 2 litros.',preco:15,foto:''},
{id:46,cat:'bebidas',nome:'Poty 600ml',desc:'Refrigerante Poty 600ml.',preco:7,foto:''},
{id:47,cat:'bebidas',nome:'Poty 2 Litros',desc:'Refrigerante Poty 2 litros.',preco:12,foto:''},
{id:48,cat:'bebidas',nome:'Roller 2 Litros',desc:'Refrigerante Roller 2 litros.',preco:12,foto:''},
{id:49,cat:'bebidas',nome:'Refrigerante Lata',desc:'Refrigerante em lata gelado.',preco:6,foto:''},
{id:50,cat:'bebidas',nome:'Suco Del Valle 600ml',desc:'Suco Del Valle 600ml.',preco:6,foto:''},
{id:51,cat:'bebidas',nome:'Suco Del Valle 1L',desc:'Suco Del Valle 1 litro.',preco:10,foto:''},
{id:52,cat:'bebidas',nome:'Suco Pomar 1L',desc:'Suco Pomar 1 litro.',preco:15,foto:''},
{id:53,cat:'bebidas',nome:'H2O',desc:'Bebida H2O.',preco:8,foto:''},
{id:54,cat:'bebidas',nome:'Água',desc:'Água mineral.',preco:4,foto:''},
{id:55,cat:'bebidas',nome:'Antarctica 1L',desc:'Refrigerante Antarctica 1 litro.',preco:8.5,foto:''},
{id:56,cat:'bebidas',nome:'Cerveja Barrigudinha',desc:'Cerveja Barrigudinha.',preco:5,foto:''},
{id:57,cat:'bebidas',nome:'Cerveja Lata',desc:'Cerveja em lata gelada.',preco:6,foto:''},
{id:58,cat:'adicionais',nome:'Adic. Bacon',desc:'Adicional de bacon crocante.',preco:5,foto:''},
{id:59,cat:'adicionais',nome:'Adic. Queijo',desc:'Adicional de queijo.',preco:5,foto:''},
{id:60,cat:'adicionais',nome:'Adic. Hambúrguer',desc:'Adicional de hambúrguer 120g.',preco:6,foto:''},
{id:61,cat:'adicionais',nome:'Adic. Cheddar',desc:'Adicional de cheddar.',preco:4,foto:''},
{id:62,cat:'adicionais',nome:'Adic. Calabresa',desc:'Adicional de calabresa.',preco:5,foto:''},
{id:63,cat:'adicionais',nome:'Adic. Alface',desc:'Adicional de alface.',preco:2.5,foto:''},
{id:64,cat:'adicionais',nome:'Adic. Tomate',desc:'Adicional de tomate.',preco:2.5,foto:''},
{id:65,cat:'adicionais',nome:'Adic. Salsicha',desc:'Adicional de salsicha.',preco:4,foto:''},
{id:66,cat:'adicionais',nome:'Adic. Ovo',desc:'Adicional de ovo.',preco:2,foto:''},
{id:67,cat:'adicionais',nome:'Adic. Catupiry',desc:'Adicional de catupiry.',preco:4,foto:''}
];
